core/urls.py
from django.conf.urls import url
from django.urls import path
from meeting_room.views import minutes, agenda

urlpatterns = [
    # path("", dashboard, name="dashboard"),
    path(r"agenda", agenda, name="agenda"),
    path(r"minutes/", minutes, name="minutes"),
]

meeting_room/urls.py
from django.urls import path
from .views import meeting_chat_room, room, upload_file

app_name = 'meeting_room'

urlpatterns = [
    path('', room, name='room'),
    # path('room/<int:meeting_id>/', views.meeting_chat_room, name='meeting_chat_room'),
    path('chat/<int:meeting_id>/', meeting_chat_room, name='meeting_chat_room'),
    # path('room/<str:room_name>/', room, name='room'),
    path('meeting/upload_document/', upload_file, name='upload_document'),
]

meetingplus/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
# from minutes.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("accounts/", include("authentication.urls")), # Auth routes - login / register
    # path("", include('core.urls')),
    path("meeting/", include('core.urls')),
    path("", include('meeting_room.urls', namespace='room')),
    path("meeting/", include('document.urls')),
]

#Add URL maps to redirect the base URL to our application
# from django.views.generic import RedirectView
# urlpatterns += [
#     path('', RedirectView.as_view(url='meeting/', permanent=True)),
# ]

# Use static() to add url mapping to serve static files during development (only)

from django.conf.urls.static import static
from core import views as core_views
# urlpatterns = i18n_patterns(
#     # other URL configuration rules...
#     path("js-settings/", core_views.js_settings,
#     name="js_settings"),
# )
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

meetingplus/templates/includes/fixed-plugin.html
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-upload fa-2x"> </i>
        Upload Document
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Filters</li>
        <form method = 'POST' class="col s12" enctype="multipart/form-data">
  
          {% csrf_token %}
    
          {{new_form.as_p}}
          <div class="form-group">
            <label for="formGroupExampleInput">Example label</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input">
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput2">Another label</label>
            <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
          </div>
          <!--Below is our main file upload input -->
          <div class="custom-file">
            <input type="file" name="document" id="document">
            <!-- <label class="custom-file-label" for="document">Choose file</label> -->
          </div>
          <li class="button-container">
            <button type="submit" class="btn btn-primary btn-block">Publish</button>
          </li>
        </form>
      </ul>
    </div>
  </div>

meetingplus/templates/includes/footer.html
    <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>

              <li>
                <a target="_blank" rel="noopener noreferrer" >
                   MeetingPlus
                </a>
              </li>

            </ul>
          </nav>
          <div class="copyright float-right">
            &copy; 2021
          </div>
        </div>
    </footer>

meetingplus/templates/includes/navigation.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end">
          {% if request.user.is_authenticated %}

            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another Notification</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}" >Log out</a>
                </div>
              </li>
            </ul>

          {% endif %}
          </div>
        
        </div>
      </nav>

meetingplus/templates/includes/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        function postDocument(){console.log('JussiPussi')};
        $sidebar = $('.sidebar');
        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

        if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
          if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
            $('.fixed-plugin .dropdown').addClass('open');
          }

        }
        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);

        });
      });
    });
  </script>
  

meetingplus/templates/includes/scripts.html
  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js"></script>
  <script src="/static/assets/js/core/popper.min.js"></script>
  <script src="/static/assets/js/core/bootstrap-material-design.min.js"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!-- Plugin for the momentJs  -->
  <script src="/static/assets/js/plugins/moment.min.js"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="/static/assets/js/plugins/sweetalert2.js"></script>
  <!-- Forms Validations Plugin -->
  <script src="/static/assets/js/plugins/jquery.validate.min.js"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="/static/assets/js/plugins/jquery.bootstrap-wizard.js"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="/static/assets/js/plugins/bootstrap-selectpicker.js"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="/static/assets/js/plugins/bootstrap-datetimepicker.min.js"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="/static/assets/js/plugins/jquery.dataTables.min.js"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="/static/assets/js/plugins/bootstrap-tagsinput.js"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="/static/assets/js/plugins/jasny-bootstrap.min.js"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="/static/assets/js/plugins/fullcalendar.min.js"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="/static/assets/js/plugins/jquery-jvectormap.js"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="/static/assets/js/plugins/nouislider.min.js"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <!-- Library for adding dinamically elements -->
  <script src="/static/assets/js/plugins/arrive.min.js"></script>
  <!-- Chartist JS -->
  <script src="/static/assets/js/plugins/chartist.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/assets/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
  <!-- markdown-it for building charts -->
  <script src="/static/assets/js/markdown-it.min.js"></script>
  <!-- custom -->
  <script src='/static/lib/webviewer.min.js'></script>

meetingplus/templates/includes/scriptsCustom.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        function postDocument(){console.log('JussiPussi')};
        $('#openUploadDocumentModalButton').click(function(event) {
          var modal = $('#uploadDocumentModal');
          var url = `http://${window.location.host}/meeting/upload_document/`
          console.log(url)
          $.ajax({
              type: "GET",
              url: url
          }).done(function(data, textStatus, jqXHR) {
              modal.find('.modal-body').html(data);
              modal.modal('show');
              formAjaxSubmit(modal, url);
          }).fail(function(jqXHR, textStatus, errorThrown) {
              console.log(errorThrown);
          });
        });

        function formAjaxSubmit(modal, endpoint) {
          var form = modal.find('.modal-body form');
          var myForm = document.getElementById('uploadDocumentForm');
          var footer = $(modal).find('.modal-footer');

          // bind to the form’s submit event
          $(myForm).on('submit', function(event) {
            let myForm = document.getElementById('uploadDocumentForm');
            let formData = new FormData(myForm)
            let myFile = document.getElementById('id_file');  // Our HTML files' ID
            // Get the files from the form input
            var files = myFile.files;
            // Select only the first file from the input array
            var file = files[0];
            // Add the file to the AJAX request
            // formData.append('theDocument', file, file.name);
            console.log("create post is working!") // sanity check
            var url = `http://${window.location.host}/meeting/upload_document/`

            // prevent the form from performing its default submit action
            event.preventDefault();
            footer.addClass('loading');
            formData.set('meeting_id', 1)
            // either use the action supplied by the form, or the original rendering url
            // var url = $(this).attr('action') || endpoint;
            console.log(formData.values());
            // serialize the form’s content and sent via an AJAX call
            // using the form’s defined method
            $.ajax({
              url : url, // the endpoint
              type : "POST", // http method
              headers: {'X-CSRFToken': '{{ csrf_token }}'},
              data : formData,
              cache: false,
              processData: false,
              contentType: false,
              success: function(json) {
                  // If the server sends back a successful response,
                  // we need to further check the HTML received
                  console.log(json)
                  // If xhr contains any field errors, the form did not
                  // validate successfully, so we update the modal body
                  // with the new form and its error
                  if ($(xhr).find('.has-error').length > 0) {
                      $(modal).find('.modal-body').html(xhr);
                      // formAjaxSubmit(modal, url);
                  } else {
                      // otherwise, we've done and can close the modal
                      $(modal).modal('hide');
                  }
              },
              error: function(xhr, ajaxOptions, thrownError) {
                $(modal).modal('hide');
                console.log(`Error: ${xhr}, ${ajaxOptions}, ${thrownError}`);
              },
              complete: function() {
                  footer.removeClass('loading');
              }
            });
          });
        }
          
   
       });
    });
  </script>

<script type="text/javascript">
  function showDocumentFunction(documentId){
  const viewerElement = document.getElementById('viewer');
  let annotManager = null;
  const DOCUMENT_ID = documentId;
  const protocol = window.location.protocol;
  const port = window.location.port;
  const hostName = window.location.hostname;
  console.log('{{ request.user }}')
  const url = `ws://${hostName}:${port}/ws/meeting/document/${documentId}/`;
  const connection = new WebSocket(url);
  console.log(connection);
  user = '{{ request.user }}';
  const serializer = new XMLSerializer();

  connection.onerror = error => {
      console.warn(`Error from WebSocket: ${error}`);
  }
  console.log(url, `http://${hostName}:${port}{{ document_path }}`, documentId)
  connection.addEventListener("open", function(e){
    console.log("Public Public ChatSocket OPEN")
        // join chat room
        if("{{request.user.is_authenticated}}"){
            connection.send(JSON.stringify({
                "command": "join",
                "documentId": documentId
            }));
        }
      })

  WebViewer({
  path: 'static/lib', // path to the PDFTron 'lib' folder
  initialDoc: `http://${hostName}:${port}{{ document_path }}`,
  // initialDoc: 'https://pdftron.s3.amazonaws.com/downloads/pl/webviewer-demo.pdf',
  documentXFDFRetriever: async () => {
      const info = await loadXfdfStrings(DOCUMENT_ID);
      // console.log('info',info);
      return info.messages.map((row) => row.xfdfString);
  },
  }, viewerElement).then( instance => {

  // Instance is ready here
  console.log(instance);
  instance.openElements(['leftPanel']);
  annotManager = instance.docViewer.getAnnotationManager();
  // Assign a random name to client
  annotManager.setCurrentUser(user);
  annotManager.on('annotationChanged', async e => {
      // If annotation change is from import, return
      if (e.imported) {
      return;
      }

      const xfdfString = await annotManager.exportAnnotCommand();
      // Parse xfdfString to separate multiple annotation changes to individual annotation change
      const parser = new DOMParser();
      const commandData = parser.parseFromString(xfdfString, 'text/xml');
      const addedAnnots = commandData.getElementsByTagName('add')[0];
      const modifiedAnnots = commandData.getElementsByTagName('modify')[0];
      const deletedAnnots = commandData.getElementsByTagName('delete')[0];

      // List of added annotations
      addedAnnots.childNodes.forEach((child) => {
      sendAnnotationChange(child, 'add');
      });

      // List of modified annotations
      modifiedAnnots.childNodes.forEach((child) => {
      sendAnnotationChange(child, 'modify');
      });
      
      // List of deleted annotations
      deletedAnnots.childNodes.forEach((child) => {
      sendAnnotationChange(child, 'delete');
      });
  });

  connection.onmessage = async (message) => {
      const annotation = JSON.parse(message.data);
      const annotations = await annotManager.importAnnotCommand(annotation.xfdfString);
      await annotManager.drawAnnotationsFromList(annotations);
    }
  });

  const loadXfdfStrings = (documentId) => {
      return new Promise((resolve, reject) => {
          fetch(`/meeting/document/messages/${documentId}/`, {
          method: 'GET',
          })
          .then((res) => {
              if (res.status < 400) {
                  res.json().then(xfdfStrings => {
                  resolve(xfdfStrings);
                  });
              } else {
                  reject(res);
              }
          })
      });
  };


  // wrapper function to convert xfdf fragments to full xfdf strings
  const convertToXfdf = (changedAnnotation, action) => {
  let xfdfString = `<?xml version="1.0" encoding="UTF-8" ?><xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve"><fields />`;
  if (action === 'add') {
      xfdfString += `<add>${changedAnnotation}</add><modify /><delete />`;
  } else if (action === 'modify') {
      xfdfString += `<add /><modify>${changedAnnotation}</modify><delete />`;
  } else if (action === 'delete') {
      xfdfString += `<add /><modify /><delete>${changedAnnotation}</delete>`;
  }
  xfdfString += `</xfdf>`;
  return xfdfString;
  }

  // helper function to send annotation changes to WebSocket server
  const sendAnnotationChange = (annotation, action) => {
      console.log('messageeeeeee', annotation, action);
      var state = annotation.getAttribute('state');
      var inreplyto = annotation.getAttribute('inreplyto')
      console.log(state, inreplyto);
      if (annotation.nodeType !== annotation.TEXT_NODE) {
          const annotationString = serializer.serializeToString(annotation);
          connection.send(JSON.stringify({
            command: "send",
            documentId: DOCUMENT_ID,
            annotationId: annotation.getAttribute('name'),
            xfdfString: convertToXfdf(annotationString, action)
          }));
      }
  }
}

</script>

meetingplus/templates/includes/sidebar.html
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="/static/assets/img/sidebar-1.jpg">
      <div class="logo">
        <a rel="noopener noreferrer" 
           href="/" class="simple-text logo-normal">
          Meeting Plus
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
        {% if request.user.is_authenticated %} 
        <li class="nav-item {% if 'ui-typography' in segment %} active {% endif %}">
          <i class="fas fa-download"></i>
          <a type="button" id="openUploadDocumentModalButton" class="btn btn-outline-primary">
            Upload Document
          </a>
        </li>
        <li class="nav-item {% if 'ui-icons' in segment %} active {% endif %}">
          <a class="nav-link" href="{% url 'agenda' %}">
            <i class="material-icons">bubble_chart</i>
            <p>Agenda</p>
          </a>
        </li>
        <li class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
          <a class="nav-link" href="{% url 'minutes' %}">
            <i class="material-icons">content_paste</i>
            <p>Minutes</p>
          </a>
        </li>
        <li class="nav-item {% if 'ui-typography' in segment %} active {% endif %}">
          <div class="nav-link" id="showDocumentButton">
            <i class="material-icons">library_books</i>
            <p>Documents</p>
          </div>
          {% if meeting_documents %}
          <ol>
            {% for document in meeting_documents %}
              <li>
                <a onclick="showDocumentFunction('{{document.id}}')">
                  {{document.name}}
                </a>
              </li>
            {% endfor %}
          </ol>
          {% else %}
            <p>There are no documents.</p>
          {% endif %}
        </li>
        <li class="nav-item {% if 'ui-notifications' in segment %} active {% endif %}">
          <a class="nav-link" href="{% url 'room:meeting_chat_room' 1 %}">
            <i class="material-icons">notifications</i>
            <p>Chat</p>
          </a>
        </li>
        <li class="nav-item {% if 'index' in segment %} active {% endif %}">
          <a class="nav-link" href="/">
            <i class="material-icons">dashboard</i>
            <p>Dashboard</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'logout' %}" >
            <i class="material-icons">directions_run</i>
            <p>Logout</p>
          </a>
        </li>

        {% else %}

          <li class="nav-item active">
            <a class="nav-link" 
               target="_blank" rel="noopener noreferrer"  
               href="">
              <i class="material-icons">unarchive</i>
              <p>MEETING PLUS</p>
            </a>
          </li>          

        {% endif %}
        </ul>
      </div>

    </div>